// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddShortcut(arg1) {
  return window['go']['main']['App']['AddShortcut'](arg1);
}

export function AddShortcutFromBase64(arg1) {
  return window['go']['main']['App']['AddShortcutFromBase64'](arg1);
}

export function ClearConnectionLogs(arg1) {
  return window['go']['main']['App']['ClearConnectionLogs'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClientStates() {
  return window['go']['main']['App']['GetClientStates']();
}

export function GetConnectionLogs(arg1) {
  return window['go']['main']['App']['GetConnectionLogs'](arg1);
}

export function GetDefaultLogDir() {
  return window['go']['main']['App']['GetDefaultLogDir']();
}

export function GetGuiSettings() {
  return window['go']['main']['App']['GetGuiSettings']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function RemoveShortcut(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveShortcut'](arg1, arg2, arg3);
}

export function SaveClientStates(arg1) {
  return window['go']['main']['App']['SaveClientStates'](arg1);
}

export function SaveGuiSettings(arg1) {
  return window['go']['main']['App']['SaveGuiSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleClient(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ToggleClient'](arg1, arg2, arg3, arg4, arg5);
}
