// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddShortcut(arg1:any):Promise<void>;

export function AddShortcutFromBase64(arg1:string):Promise<void>;

export function GetShortcuts():Promise<Array<main.ShortClient>>;

export function RemoveShortcut(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestConnection(arg1:any):Promise<boolean>;

export function ToggleClient(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;
