// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddShortcut(arg1:string):Promise<void>;

export function AddShortcutFromBase64(arg1:string):Promise<void>;

export function ClearConnectionLogs(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetClientStates():Promise<Record<string, string>>;

export function GetConnectionLogs(arg1:string):Promise<Array<main.ConnectionLog>>;

export function GetDefaultLogDir():Promise<string>;

export function GetGuiSettings():Promise<main.GuiSettings>;

export function GetShortcuts():Promise<Array<main.ShortClient>>;

export function RemoveShortcut(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveClientStates(arg1:Record<string, string>):Promise<void>;

export function SaveGuiSettings(arg1:main.GuiSettings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ToggleClient(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;
